- name: "Copy Files" 
  copy:
    src: ~/artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz
    dest: ~/
- name: "Backend Deploy"
  shell: |
    tar -xzvf ~/artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start

