- name: "Creates backend folder"
  file:
    path: ~/backend
    state: directory

- name: "Unarchive files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Install NodeJS Depends"
  shell: |
    pwd
    cd ~/backend
    npm i
  

- name: "Backend Deploy"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
  register: execute_node 

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save


