- name: "Creates backend folder"
  file:
    path: ~/backend
    state: directory

- name: "Copy Artifact" 
  copy:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Unarchive files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "Install NodeJS Depends"
  shell: |
    cd ~/backend
    npm i

- name: "Backend Deploy"
  shell: |
    cd ~/backend/dist
    pm2 stop default
    pm2 start main.js
    

